### ISSUE TITLE
LACP doesn't work on vQFX 18.4R1.8

### ISSUE THREAD

**Issue by akher1** [Juniper/wistar#52] opened 2019-08-07 12:12 UTC
I tested many times in my lab and found that LACP does not work on vQFX 18.4R1.8.

All the sides shows TX packets but there's nothing in the RX

root@vQFX1-MC-LAG1# run show lacp statistics interfaces 
Aggregated interface: ae1
    LACP Statistics:       LACP Rx     LACP Tx   Unknown Rx   Illegal Rx 
      xe-0/0/2                   0        9111            0            0

root@vQFX2-MC-LAG2# run show lacp statistics interfaces 
Aggregated interface: ae1
    LACP Statistics:       LACP Rx     LACP Tx   Unknown Rx   Illegal Rx 
      xe-0/0/2                   0        4290            0            0

root@vQFX3-SERVER-MC# run show lacp statistics interfaces    
Aggregated interface: ae1
    LACP Statistics:       LACP Rx     LACP Tx   Unknown Rx   Illegal Rx 
      xe-0/0/0                   0         196            0            0
      xe-0/0/1                   0         195            0            0

{master:0}[edit]

**Comment by akher1** [comment] 2019-08-09 06:43
any update

**Comment by akher1** [comment] 2019-08-12 05:54
Interfaces don't come up with force-up as well.

**Comment by dmontagner** [comment] 2019-08-12 06:24
@akher1 this is not a vQFX problem. This is a protection enabled by default at the Linux kernel that prevents certain multicast ethernet address to be forwarded.

This message here explain the problem: https://lists.linuxfoundation.org/pipermail/bridge/2015-January/009456.html

I made the following changes on the source code of my Linux kernel and recompiled it.

```
/*
* #define BR_GROUPFWD_RESTRICTED (BR_GROUPFWD_STP | BR_GROUPFWD_MACPAUSE | \
*				BR_GROUPFWD_LACP)
*/
#define BR_GROUPFWD_RESTRICTED 0x0000u
```

After booting my host OS with a kernel with the changes above in place, I was able to get LACP and LLDP working.

**Comment by dmontagner** [comment] 2019-08-12 06:26
Closing this issue as it is related to Linux kernel and not vQFX.

**Closed as completed by dmontagner** 2019-08-12 06:26 UTC

**Comment by akher1** [comment] 2019-08-12 17:37
I am not a developer, How can I get it fixed in my setup?

**Comment by akher1** [comment] 2019-08-12 17:48
I understand this is not a vQFX issue but this is impacting the vQFX functionality and this has to be fixed. Kindly provide the fixed version or patch for this issue.

Regards,
Ankur

**Comment by Sidiox** [comment] 2019-08-12 17:56
As @dmontagner says, the issue is not part of the Wistar software. Your Wistar software runs on your operating system and the problem is in the operating system, specifically in the kernel. 

I suggest you read this blog post which might help you: https://interestingtraffic.nl/2017/11/16/playing-around-with-wistar/

**Comment by akher1** [comment] 2019-08-13 05:34
Thanks Sidiox, I got it!

Thanks again for providing me the right link with directions.

Regards,
Ankur
